apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-cstor-pvc
spec:
  storageClassName: openebs-cstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
