apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cstor-pvc-volume
  volumes:
    - name: cstor-pvc-volume
      persistentVolumeClaim:
        claimName: openebs-cstor-pvc
